#pragma once

enum class PACKET_ID : unsigned short
{
	PK_C2S_LOGIN,
	PK_S2C_LOGIN,
	PACKET_IS_HOST,
	PACKET_IS_LOGIN_REQ,
	PACKET_NEW_PLAYER,
	PACKET_USER_INIT,
	PACKET_NEW_OBJ,
	PACKET_HOST_OBJ_INFO,
	PACKET_SEND_STAT_INFO,
	PACKET_SEND_POS_INFO,
	PACKET_MOVE,
	PACKET_ATT,
};
